sudo: required

services:
- docker

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y bzip2 python-pip
- sudo pip install --upgrade pip
- sudo -H pip install --ignore-installed PyYAML
- sudo pip install yq
- curl -sl https://raw.githubusercontent.com/wise2c-dev/wise2c-config/master/config.yaml -o /tmp/config.yaml
- KUBE_VERSION=$(cat /tmp/config.yaml |  yq -r '.branchs[] | select(.branch == "release-1.15")|.kube_version')
- DOCKER_TAG=${KUBE_VERSION}

script:
- bash init.sh
- docker build -t wisecloud/playbook:$DOCKER_TAG .
- docker tag wisecloud/playbook:$DOCKER_TAG registry.cn-hangzhou.aliyuncs.com/wise2c-test/playbook:$DOCKER_TAG
- docker login -u $ALIYUN_USERNAME -p $ALIYUN_PASSWORD registry.cn-hangzhou.aliyuncs.com
- docker push registry.cn-hangzhou.aliyuncs.com/wise2c-test/playbook:$DOCKER_TAG
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push wisecloud/playbook:$DOCKER_TAG
