sudo: required

services:
- docker

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y bzip2

script:
- bash init.sh
- docker build -t wisecloud/playbook:v1.11.6-e1.6.1 .

deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push wisecloud/playbook:v1.11.6-e1.6.1
  on:
    all_branches: true
    #condition: "$TRAVIS_BRANCH =~ ^v[0-9]+\\.[0-9]+(\\.[0-9]+)?(-\\S*)?$"
