sudo: required

services:
- docker

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y bzip2

script:
- bash init.sh
- docker build -t wise2c/playbook:v1.13.1 .

deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push wise2c/playbook:v1.13.1
  on:
    all_branches: true
#    condition: "$TRAVIS_BRANCH =~ ^v[0-9]+\\.[0-9]+(\\.[0-9]+)?(-\\S*)?$"
