endpoint: {{ if eq (print .Property.endpoint) "" -}}
          {{ (index .Hosts.self 0).IP }}
          {{- else -}}
          {{ .Property.endpoint }}
          {{- end }}
user: {{ .Property.username }}
password: {{ .Property.password }}
          